### ISSUE TITLE
Write the portion of RecCoin.js test script to carry out unit tests on the "approve" function.

### ISSUE THREAD

**Issue by Adesdesk** [Grandida-Projects/reccoin-backend#26]
Please study and understand the RecCoin.sol contract file of this repository and update RecCoin.js with your written unit tests for the "approve" function (on line 75). This function by extension calls the _approve function (on line 142). You should bear this in mind in carrying out your tests.

Please get back in touch if there is anything to clarify.

**Comment by Adesdesk** [comment]
I have written and updated the repo with the needed tests for the said function, so you can recover fully and possibly get back to work on subsequently assigned tasks.
Have a nice weekend.

**Comment by el-ken** [comment]
Thank you so much Ade,
I’m glad 


Sent from Yahoo Mail for iPhone


On Saturday, May 20, 2023, 10:25 PM, Adeola ***@***.***> wrote:




I have written and updated the repo with the needed tests for the said function, so you can recover fully and possibly get back to work on subsequently assigned tasks.
Have a nice weekend.
