### ISSUE TITLE
Write the portion of RecCoin.js test script to carry out unit tests on the "burn" function of RecCoin.sol

### ISSUE THREAD

**Issue by Adesdesk** [Grandida-Projects/reccoin-backend#27]
Please study and understand the RecCoin.sol contract file of this repository and update RecCoin.js with your written unit tests for the "burn" function (on line 114). This function by extension calls the _burn function (on line 156). You would want to bear this in mind in carrying out your tests.

Please get back in touch if there is anything more to clarify.

**Comment by Joshuailuma** [comment]
The test script has been written for the burn function.

**Comment by Adesdesk** [comment]
Thanks!
Please expect to attend to more tasks as subsequent smart contracts are turned in.
