### ISSUE TITLE
Write the portion of Recycle.js test script to carry out unit tests on the "editCompany" and "updateCompanyMinWeightRequirement" functions.

### ISSUE THREAD

**Issue by Adesdesk** [Grandida-Projects/reccoin-backend#69]
Please study and understand the Recycle.sol contract file of this repository and update Recycle.js with your written unit tests for the "editCompany" and "updateCompanyMinWeightRequirement" functions. (starting on lines 299 and 343 respectively).

Kindly get back in touch if there is anything to clarify.
Thanks.

**Comment by Joshuailuma** [comment]
Done

**Comment by Adesdesk** [comment]
Updates received. Thanks.

**Comment by Adesdesk** [comment]
There are 10 more functions from the Recycle.sol contract which we still have to work on. Please proceed with writing tests for the functions "registerPicker", "getPicker", and "getRegisteredPickerCount" (featured on lines 387, 412, and 420 respectively).

**Comment by Joshuailuma** [comment]
Done. Kindly review

**Comment by Adesdesk** [comment]
Okay. Thanks for making this happen.
